/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.lette1394.mediaserver;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

import org.junit.jupiter.api.Test;


class AppTest {
  @Test
  void test() {
  }
}
